### ISSUE TITLE
Upstreaming MPCC controller

### ISSUE THREAD

**Issue by hidmic** [ekumenlabs/safe-control-gym#8]
## Description

Now that the competition is over, perhaps we can contribute back to the [utiasDSL/safe-control-gym](https://github.com/utiasDSL/safe-control-gym) community and upstream our MPCC controller implementation. 

## Definition of Done

- [ ] Check with [utiasDSL/safe-control-gym](https://github.com/utiasDSL/safe-control-gym) maintainers.
- [ ] Reshape the [local](https://github.com/ekumenlabs/safe-control-gym/blob/ekumenlabs/submission/competition/mpcc_controller.py) MPCC controller implementation to fit [utiasDSL/safe-control-gym](https://github.com/utiasDSL/safe-control-gym) controllers' structure.
- [ ] Submit it :rocket:

**Comment by glpuga** [comment]
Why did we close this?

**Comment by hidmic** [comment]
Opened https://github.com/ekumenlabs/RnD/issues/160.
